// Code generated by ImplGen.
// Source: book_repository.go

package mongo

import (
	context "context"

	"github.com/coocn-cn/leanote/app/info"
	model "github.com/coocn-cn/leanote/app/note/model"
)

type tagMutation struct {
	*baseMutation
}

func newtagMutation(data model.TagData, db *info.NoteTag) *tagMutation {
	return &tagMutation{baseMutation: newbaseMutation(data, db)}
}

func (m *tagMutation) db() *info.NoteTag {
	return m.baseMutation.db.(*info.NoteTag)
}

func (m *tagMutation) Data(ctx context.Context) (data model.TagData, err error) {
	return data, m.baseMutation.Data(ctx, &data)
}
