// Code generated by ImplGen.
// Source: note_repository.go

package mongo

import (
	context "context"

	"github.com/coocn-cn/leanote/app/db"
	"github.com/coocn-cn/leanote/app/info"
	model "github.com/coocn-cn/leanote/app/note/model"
	repository "github.com/coocn-cn/leanote/app/note/repository"
	"github.com/coocn-cn/leanote/pkg/errcode"
	"github.com/coocn-cn/leanote/pkg/log"
	"gopkg.in/mgo.v2"
	"gopkg.in/mgo.v2/bson"
)

type note struct {
	collection *mgo.Collection
}

// NewNote create a new note object
func NewNote(ctx context.Context) *note {
	obj := &note{
		collection: db.Notes,
	}

	return obj
}

// New is 初始化一个新的领域对象
func (m *note) New(ctx context.Context, data model.NoteData) *model.Note {
	dbData := newnoteData(data, nil, m)
	return model.NewNote(dbData)
}

// Count is 获取符合 Predicater 条件的领域对象的个数
func (m *note) Count(ctx context.Context, predicate repository.Predicater) (int, error) {
	return db.Count(db.Notebooks, m.predicates(ctx, predicate)), nil
}

// Find is 加载一个符合 Predicater 条件的领域对象
func (m *note) Find(ctx context.Context, predicate repository.Predicater) (*model.Note, error) {
	notes, err := m.FindAll(ctx, predicate)
	if err != nil {
		return nil, err
	}

	if len(notes) == 0 {
		return nil, nil
	}

	return notes[0], nil
}

// FindAll is 加载所有符合 Predicater 条件的领域对象
func (m *note) FindAll(ctx context.Context, predicate repository.Predicater) ([]*model.Note, error) {
	notes := []info.Note{}
	m.collection.Find(m.predicates(ctx, predicate)).All(&notes)

	resp := make([]*model.Note, 0, len(notes))
	for i := range notes {
		dbData := newnoteData(model.NoteData(notes[i]), &notes[i], m)
		resp = append(resp, model.NewNote(dbData))
	}

	return resp, nil
}

// Save is 保存领域对象到仓储
func (m *note) Save(ctx context.Context, models ...*model.Note) error {
	for _, model := range models {
		mut := model.NoteMutation.(*noteData)
		saveData, err := mut.Data(ctx)
		if err != nil {
			return err
		}

		if mut.db() != nil {
			// 更新之
			if ok := db.UpdateByIdAndUserIdMap(m.collection, mut.db().NoteId.Hex(), mut.db().UserId.Hex(), mut.updates); !ok {
				return errcode.NotFound(ctx, "更新对象失败", mut.db, saveData)
			}
		} else {
			// 保存之
			db.Insert(m.collection, info.Note(saveData))
		}

		// 更新 model.mutation 对象状态
		*mut = *newnoteData(saveData, (*info.Note)(&saveData), m)

		log.G(ctx).WithField("old", mut.old).WithField("new", saveData).Info("Note Save")
	}

	return nil
}

// Delete is 删除仓储中的领域对象
func (m *note) Delete(ctx context.Context, models ...*model.Note) error {
	for _, model := range models {
		data, err := model.Data(ctx)
		if err != nil {
			return err
		}

		if ok := db.DeleteByIdAndUserId(m.collection, data.NoteId.Hex(), data.UserId.Hex()); !ok {
			return errcode.NotFound(ctx, "删除对象失败", data)
		}
	}

	return nil
}

// DeleteID is 通过ID删除仓储中的领域对象
func (m *note) DeleteID(ctx context.Context, ids ...uint64) error {
	// TODO: note.DeleteID(ctx context.Context, ids ...uint64) error Not implemented

	panic("note.DeleteID(ctx context.Context, ids ...uint64) error Not implemented")
}

func (m *note) predicates(ctx context.Context, predicate repository.Predicater) bson.M {
	switch predicate.Predicate() {
	case "NoteID":
		params := predicate.Data().(map[string]string)
		return bson.M{"_id": bson.ObjectIdHex(params["id"])}
	case "NoteIDAndNotDelete":
		params := predicate.Data().(map[string]string)
		return bson.M{"_id": bson.ObjectIdHex(params["id"]), "IsDeleted": false}
	case "NoteIDs":
		params := predicate.Data().(map[string][]string)

		ids := params["ids"]
		hexIDs := make([]bson.ObjectId, 0, len(ids))
		for _, v := range ids {
			hexIDs = append(hexIDs, bson.ObjectIdHex(v))
		}

		return bson.M{"_id": bson.M{"$in": hexIDs}}
	case "NoteBookID":
		params := predicate.Data().(map[string]string)
		return bson.M{"NotebookId": bson.ObjectIdHex(params["bookID"])}
	}

	panic(errcode.Unimplemented(ctx, "加载条件未实现", predicate.Predicate()).Error())
}
