// Code generated by ImplGen.
// Source: book_repository.go

package mongo

import (
	context "context"

	"github.com/coocn-cn/leanote/app/info"
	"github.com/coocn-cn/leanote/app/tag/model"
)

type tagMutation struct {
	*baseMutation
}

func newtagMutation(data model.TagData, db *info.Tag) *tagMutation {
	return &tagMutation{baseMutation: newbaseMutation(data, db)}
}

func (m *tagMutation) db() *info.Tag {
	return m.baseMutation.db.(*info.Tag)
}

func (m *tagMutation) Data(ctx context.Context) (data model.TagData, err error) {
	return data, m.baseMutation.Data(ctx, &data)
}
