on:
  push:
    branches:
    - master
    - release/*
name: build-release
jobs:
  release-drafter:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
            name: build-pkg
            path: ./output/leanote